### ISSUE TITLE
Improper packaging

### ISSUE THREAD

**Issue by ncovercash** [N3XT191/react-multi-progress#2]
This package was exactly what I was looking for and I was excited to get started using it, however, it seems like this package is not properly deployed to NPM.  Adding it to a fresh project results in `/node_modules/react-multi-progress` containing only `README.md`, `LICENSE`, and `package.json` -- it seems like the `dist` compiled files were not published.

Reverting to v1.0.4 fixed this.

**Comment by N3XT191** [comment]
Whoops, will fix later today!

**Comment by N3XT191** [comment]
v1.1.6 should have this fixed, works in my demo project, let me know if it still doesn't work for you

**Comment by ncovercash** [comment]
Woo, thanks a ton!
