### ISSUE TITLE
Feature request: accept style prop

### ISSUE THREAD

**Issue by ncovercash** [N3XT191/react-multi-progress#3]
It'd be really cool if the `MultiProgress` component could accept an arbitrary `style` prop (my use case would make `box-shadow` really helpful)!

**Comment by N3XT191** [comment]
Good suggestion. I assume a className prop would achieve the same? most of the UI libraries I know do the custom styling through classnames so I assume that is the better way 😅

**Comment by ncovercash** [comment]
Sure!  That'd be a great option, too

**Comment by N3XT191** [comment]
Alright, both the ProgressBar and the ProgressElement now accept a className prop that gets passed through to the container and the individual elements respectively. Tested with box-shadow (see http://progress.bitter.li).

Will update the README docs too, those currently lack the className prop
